include:
  - board: xiao_ble//zmk
    shield: splitsies_dongle
    #snippet: zmk-usb-logging
    
  - board: nice_nano//zmk
    shield: splitsies_left
    #snippet: zmk-usb-logging
    
  - board: nice_nano//zmk
    shield: splitsies_right
    #snippet: zmk-usb-logging

  - board: xiao_ble//zmk
    shield: settings_reset
    
  - board: nice_nano//zmk
    shield: settings_reset
