include:
  - board: xiao_ble
    shield: splitsies_dongle
    snippet: zmk-usb-logging
    
  - board: nice_nano_v2
    shield: splitsies_left
    
  - board: nice_nano_v2
    shield: splitsies_right

  - board: xiao_ble
    shield: settings_reset
    
  - board: nice_nano_v2
    shield: settings_reset
