include:
  - board: xiao_ble
    shield: splitsies_dongle
    snippet: zmk-usb-logging
    
  - board: nice_nano
    shield: splitsies_left
    snippet: zmk-usb-logging
    
  - board: nice_nano
    shield: splitsies_right
    snippet: zmk-usb-logging

  - board: xiao_ble
    shield: settings_reset
    
  - board: nice_nano
    shield: settings_reset
