include:
  - board: xiao_ble
    shield: splitsies_dongle
    
  - board: nice_nano
    shield: splitsies_left
    
  - board: nice_nano
    shield: splitsies_right

  - board: xiao_ble
    shield: settings_reset
    
  - board: nice_nano
    shield: settings_reset
